src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $started_at;

    /**
     * @ORM\Column(type="date")
     */
    private $ended_at;

    /**
     * @ORM\Column(type="smallint")
     */
    private $nb_seat;

    /**
     * @ORM\ManyToMany(targetEntity=Stagiaire::class, inversedBy="sessions")
     */
    private $stagiaires;

    /**
     * @ORM\ManyToMany(targetEntity=Programme::class, mappedBy="sessions")
     */
    private $programmes;

    public function __construct()
    {
        $this->stagiaires = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->ended_at;
    }

    public function setEndedAt(\DateTimeInterface $ended_at): self
    {
        $this->ended_at = $ended_at;

        return $this;
    }

    public function getNbSeat(): ?int
    {
        return $this->nb_seat;
    }

    public function setNbSeat(int $nb_seat): self
    {
        $this->nb_seat = $nb_seat;

        return $this;
    }

    /**
     * @return Collection|stagiaire[]
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(stagiaire $stagiaire): self
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires[] = $stagiaire;
        }

        return $this;
    }

    public function removeStagiaire(stagiaire $stagiaire): self
    {
        if ($this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->removeElement($stagiaire);
        }

        return $this;
    }

    /**
     * @return Collection|Programme[]
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): self
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes[] = $programme;
            $programme->addSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): self
    {
        if ($this->programmes->contains($programme)) {
            $this->programmes->removeElement($programme);
            $programme->removeSession($this);
        }

        return $this;
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Programme;
use App\Entity\Session;
use App\Entity\Stagiaire;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('started_at')
            ->add('ended_at')
            ->add('nb_seat')
            ->add('stagiaires',EntityType::class,[
                'class'=>Stagiaire::class,
                'choice_label'=>function(Stagiaire $stagiaire){
                    return $stagiaire->getName().' '.$stagiaire->getFirstname();
                },
                'multiple'=>true,
                "required"=>false
            ])
            //FIXME
            /*->add('programmes',EntityType::class,[
                'class'=>Programme::class,
                'choice_label'=>function(Programme $programme){
                    return $programme->getBlocmodulesName();
                },
                'multiple'=>true,
                "required"=>false
            ])*/
            /*BUG
            et si on passait par une page spéciale pr le programme de chaque session de formation 
            penser make:crud programme*/
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;
use App\Entity\Stagiaire;
use App\Entity\Session;
use App\Form\SessionType;
use App\Repository\SessionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/session")
 */
class SessionController extends AbstractController
{
    /**
     * @Route("/", name="session_index", methods={"GET"})
     */
    public function index(SessionRepository $sessionRepository): Response
    {
        return $this->render('session/index.html.twig', [
            'sessions' => $sessionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="session_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $session = new Session();
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($session);
            $entityManager->flush();

            return $this->redirectToRoute('session_index');
        }

        return $this->render('session/new.html.twig', [
            'session' => $session,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="session_show", methods={"GET"})
     */
    public function show(Session $session): Response
    {
        return $this->render('session/show.html.twig', [
            'session' => $session,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="session_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Session $session): Response
    {
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('session_index');
        }

        return $this->render('session/edit.html.twig', [
            'session' => $session,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="session_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Session $session): Response
    {
        if ($this->isCsrfTokenValid('delete'.$session->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($session);
            $entityManager->flush();
        }

        return $this->redirectToRoute('session_index');
    }
}

templates/session/_delete_form.html.twig
<form method="post" action="{{ path('session_delete', {'id': session.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ session.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/session/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition Session{% endblock %}

{% block body %}
    <h1>Editer Session</h1>

    {{ include('session/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('session_index') }}">Retour à la liste</a>

    {{ include('session/_delete_form.html.twig') }}
{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Session{% endblock %}

{% block body %}
    <h1>liste des sessions</h1>

    <table class="table">
        <thead>
            <tr>
                
                <th>Intitulé</th>
                <th>Commence le</th>
                <th>Finis le</th>
                <th>Nombre de places prévues</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for session in sessions %}
            <tr>
                
                <td>{{ session.title }}</td>
                <td>{{ session.startedAt ? session.startedAt|date('d-m-Y') : '' }}</td>
                <td>{{ session.endedAt ? session.endedAt|date('d-m-Y') : '' }}</td>
                <td>{{ session.nbSeat }}</td>
                <td>
                    <button><a href="{{ path('session_show', {'id': session.id}) }}">voir</a></button>
                    <button><a href="{{ path('session_edit', {'id': session.id}) }}">editer</a></button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Pas de session pour l'instant</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('session_new') }}">Créer une session</a>
{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Session{% endblock %}

{% block body %}
    <h1>Création de session</h1>

    {{ include('session/_form.html.twig') }}

    <a href="{{ path('session_index') }}">retour à la liste</a>
{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Session{% endblock %}

{% block body %}
    <h1>Session</h1>

    <table class="table">
        <tbody>
            
            <tr>
                <th>Intitulé</th>
                <td>{{ session.title }}</td>
            </tr>
            <tr>
                <th>Commencé le</th>
                <td>{{ session.startedAt ? session.startedAt|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Finis le </th>
                <td>{{ session.endedAt ? session.endedAt|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Nbre de places prévues</th>
                <td>{{ session.nbSeat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('session_index') }}">Retour à la liste</a>

    <a href="{{ path('session_edit', {'id': session.id}) }}">Editer</a>

    {{ include('session/_delete_form.html.twig') }}
{% endblock %}